apiVersion: v1
kind: Secret
metadata:
  name: social-pipeline-secrets
  namespace: social-pipeline
type: Opaque
data:
  MINIO_ROOT_USER: "bWluaW9hZG1pbg=="
  MINIO_ROOT_PASSWORD: "bWluaW9hZG1pbg=="
  S3_ACCESS_KEY: "bWluaW9hZG1pbg=="
  S3_SECRET_KEY: "bWluaW9hZG1pbg=="
  CLICKHOUSE_PASSWORD: "c29jaWFs"
  POSTGRES_USER: "YWlyZmxvdw=="
  POSTGRES_PASSWORD: "YWlyZmxvdw=="
  POSTGRES_DB: "YWlyZmxvdw=="
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6YWlyZmxvd0Bwb3N0Z3Jlcy1zZXJ2aWNlL2FpcmZsb3c="
