name: it4931-streaming
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openjdk=11
  - fastavro=1.9.4
  - pip
  - pyspark=3.5.0
  - pandas=2.1.0
  - numpy=1.24
  - requests=2.31.0
  - pytest=7.4
  - ipython=8.12
  - jupyter=1.0.0
  - jupyterlab=4.0
  - pip-tools=7.3
  - pip:
    - confluent-kafka[avro]==2.4.0
    - python-dotenv==1.0.1
