[project]
name = "social-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka==2.4.0",
    "numpy<2",
    "pyarrow==14.0.1",
    "python-dotenv==1.0.1",
    "fastapi==0.111.0",
    "boto3==1.34.131",
    "uvicorn[standard]==0.29.0",
    "prometheus-client==0.20.0",
    "redis==5.0.4",
    "langdetect==1.0.9",
    "cassandra-driver==3.29.2",
    "scikit-learn==1.5.0",
    "pandas>=2.1.0",
    "pytest==8.2.2",
    "pytest-cov==5.0.0",
    "locust==2.29.1",
    "requests==2.32.3",
]

[project.optional-dependencies]
ml = [
    "lightgbm>=4.3.0",
    "transformers>=4.40.0",
    "torch>=2.2.0",
    "sentencepiece>=0.2.0",
    "optuna>=3.6.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
