apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-anomaly
  namespace: social-pipeline
  labels:
    app: ml-anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-anomaly
  template:
    metadata:
      labels:
        app: ml-anomaly
    spec:
      initContainers:
        - name: wait-for-infra
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for API and Cassandra..."
              until nc -z api-service 8000; do sleep 2; done
              until nc -z cassandra-service 9042; do sleep 2; done
              echo "Infra ready!"
      containers:
        - name: anomaly-detector
          image: social-ml:0.1.0
          imagePullPolicy: IfNotPresent
          command:
            - python
            - -m
            - ml.anomaly_detector
          envFrom:
            - configMapRef:
                name: social-pipeline-config
            - secretRef:
                name: social-pipeline-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
