apiVersion: apps/v1
kind: Deployment
metadata:
  name: speed-streaming
  namespace: social-pipeline
  labels:
    app: speed-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speed-streaming
  template:
    metadata:
      labels:
        app: speed-streaming
    spec:
      initContainers:
        - name: wait-for-infra
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Kafka, MinIO, Redis and Elasticsearch..."
              until nc -z kafka-service 9092; do sleep 2; done
              until nc -z minio-service 9000; do sleep 2; done
              until nc -z redis-service 6379; do sleep 2; done
              until nc -z elasticsearch-service 9200; do sleep 2; done
              echo "Infra ready!"
      containers:
        - name: speed
          image: social-spark:3.5.1
          imagePullPolicy: Never
          command:
            - /opt/spark/bin/spark-submit
            - --master
            - "spark://spark-master-service:7077"
            - --driver-memory
            - 1g
            - --executor-memory
            - 512m
            - --total-executor-cores
            - "1"
            - --conf
            - spark.driver.host=$(SPARK_POD_IP)
            - --conf
            - spark.driver.bindAddress=0.0.0.0
            - --conf
            - spark.ui.port=4040
            - --conf
            - spark.driver.extraJavaOptions=-Djava.net.preferIPv4Stack=true
            - /app/speed/streaming_job.py
          envFrom:
            - configMapRef:
                name: social-pipeline-config
            - secretRef:
                name: social-pipeline-secrets
          env:
            - name: SPARK_LOCAL_IP
              value: "0.0.0.0"
            - name: SPARK_MASTER
              value: "spark://spark-master-service:7077"
            - name: SPARK_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPEED_LIGHTWEIGHT
              value: "true"
            - name: STREAM_STARTING_OFFSETS
              value: "earliest"
          resources:
            requests:
              cpu: 200m
              memory: 768Mi
            limits:
              cpu: 800m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: speed-streaming-ui-service
  namespace: social-pipeline
spec:
  ports:
    - port: 4040
      targetPort: 4040
  selector:
    app: speed-streaming
